### ISSUE TITLE
Create and submit your project using JavaScript

### ISSUE THREAD

**Issue by CodeAjay** [CodeAjay/JavaScript-Projects#1]
Create and submit your project using JavaScript

**Comment by rhinoxD** [comment]
!assign

**Comment by CodeAjay** [comment]
Assigned 

You can submit your javascript project now.

**Comment by Rishav1707** [comment]
@CodeAjay I want to add a project based on Javascript.
Shall I?

**Comment by CodeAjay** [comment]
Go ahead.
